services:
  - type: web
    name: Food-Delivery-Time-Predictor
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run main.py --server.port=$PORT --server.enableCORS=false
